# Extração dos dados das estações, e S4
___

Os dados de estações e S4 estão organizados em um servidor postgresql rodando na minha maquina local. Para permitir a utilização por outros, este notebook, além de extrair os dados do postgresql vai gerar um csv, contendo as informações sobre as estações brutas. Assim, como um dataframes pandas, um por estação, comprimido usando o formatado xz, o que forneceu a extensão "pkl.xz".

As estações válidas são aquelas que apresentam algum dado de S4, pois existem estações que não coletaram dado nenhum durante o período de aquisição.

Note assim, que este notebook não executará em um máquina onde os dados não estejam armazenados no postgresql.

In [1]:
import aacgmv2
import os
import sys
import psycopg2

import datetime as dt
import geopandas as gpd
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import seaborn as sns

from mpl_toolkits.basemap import Basemap
from itertools import chain
from tqdm import tqdm

%matplotlib inline

In [2]:
conn = psycopg2.connect(database="data-research",
                        user="data-research",
                        password="data-research",
                        host="localhost",
                        port=5432)

In [3]:
df_station = pd.read_sql_query('select * from station;', con=conn)
df_station.to_csv("./data/stations.csv")
df_station = df_station.drop(columns=["startoperation", "stopoperation", "alias", "network"])

In [4]:
query = '''select scintillation.eventdate, scintillation.s4 
           from scintillation inner join station on 
           scintillation.station = station.identificationstation 
           where station.identificationstation = '%s' 
           order by scintillation.eventdate; 
        '''
drop_aux = []
select_station_and_df_s4 = []
for i in tqdm(df_station.itertuples()):
    station = i.identificationstation
    df_aux = pd.read_sql_query(query % station, con=conn)
    if len(df_aux) == 0:
        drop_aux.append(station)
    else:
        df_aux.to_pickle("./data_s4/df_" + station + ".pkl.xz", compression='xz')

54it [2:51:04, 190.07s/it]

In [5]:
df_station = df_station[~df_station['identificationstation'].isin(drop_aux)]
df_station.to_pickle("./data/df_station.pkl")

In [6]:
df_station

,identificationstation,height,latitude,longitude,state,city
0,bov,69.180,2.833920,-60.695380,rr,boa vista
6,tfe,0.057,-3.180000,-64.440000,am,tefe
7,imp,134.720,-5.310000,-47.280000,ma,imperatriz
8,nta,0.000,-5.836162,-35.121000,rn,natal
10,pvh,1130.000,-8.490000,-63.550000,ro,porto velho
11,pln,434.340,-9.230000,-40.300000,pe,petrolina
13,afl,267.000,-9.900000,-55.900000,mt,alta floresta
14,ios,0.000,-14.470000,-39.100000,ba,ilheus
15,cub,278.000,-15.555200,-56.069800,mt,cuiaba
16,bsa,1050.000,-15.764200,-47.869400,df,brasilia
17,bhz,858.000,-19.868500,-47.869400,mg,belo horizonte
19,dou,756.120,-22.110000,-54.550000,ms,dourados
20,cpa,580.000,-22.410000,-45.000000,sp,cachoeira paulista
21,sj2,593.440,-23.207600,-45.859800,sp,sao jose dos campos
23,sta,110.100,-29.712591,-53.717206,rs,santa maria
24,14,NaN,-23.207000,-45.859000,sp,são josé dos campos(inpe)
25,26,NaN,-13.001000,-38.508000,ba,salvador
27,20,NaN,-20.497000,-54.615000,ms,campo grande
28,19,NaN,-22.120000,-51.407000,sp,presidente prudente
30,32,NaN,-20.497000,-54.615000,ms,campos grande
32,30,NaN,-21.989000,-47.334000,sp,"academia das forças aérias, pirassununga"
33,22,NaN,-22.823000,-43.238000,rj,galeão
34,5,NaN,-22.120000,-51.407000,sp,presidente prudente
35,29,NaN,-2.574000,-44.209000,ma,são luis do maranhão
37,31,NaN,-9.870000,-56.104000,mt,alta floresta
38,11,NaN,-22.823000,-43.238000,rj,macaé
40,8,NaN,-23.207000,-45.859000,sp,são josé dos campos (univap)
41,24,NaN,-3.742000,-38.539000,ce,fortaleza
42,17,NaN,-22.120000,-51.407000,sp,presidente prudente
43,28,NaN,-3.100000,-59.976000,am,manaus
44,15,NaN,-3.100000,-59.976000,am,manaus
45,16,NaN,-22.823000,-43.238000,rj,galeão
46,25,NaN,-22.318000,-46.329000,mg,inconfidentes
47,18,NaN,-22.120000,-51.407000,sp,presidente prudente
48,3,NaN,-10.200000,-48.312000,ro,palmas
49,6,NaN,-22.120000,-51.407000,sp,presidente prudente
50,4,NaN,-30.071000,-51.119000,rs,porto alegre
51,33,NaN,-22.789000,-45.220000,sp,guaratinguestá
52,1,NaN,-22.823000,-43.238000,rj,macaé
53,34,NaN,-22.823000,-43.238000,rj,galeão